pipeline:
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - chmod +x .drone/build.sh
      - .drone/build.sh ${DOCKERFILE}

  test:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - chmod +x .drone/test.sh
      - .drone/test.sh ${DOCKERFILE}

  publish:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/xataz/.docker/config.json:/root/.docker/config.json
    commands:
      - chmod +x .drone/push.sh
      - .drone/push.sh ${DOCKERFILE}
    when:
      branch: master

matrix:
  DOCKERFILE:
    - lufi
